-- CREATE OR REPLACE FUNCTION get_monthly_sum(account_from_input varchar, date_input timestamp with time zone)
--     RETURNS numeric AS
-- $$
-- BEGIN
--     RETURN (SELECT SUM(amount)
--             FROM transactions
--             WHERE EXTRACT(MONTH FROM dateime) = EXTRACT(MONTH FROM date_input)
--               AND EXTRACT(YEAR FROM dateime) = EXTRACT(YEAR FROM date_input)
--               AND account_from = account_from_input);
-- END;
-- $$ LANGUAGE plpgsql;
--
--
-- CREATE OR REPLACE FUNCTION get_monthly_sum(account_from INTEGER, transaction_date TIMESTAMP)
--     RETURNS NUMERIC AS $$
-- DECLARE
--     total_sum NUMERIC;
-- BEGIN
--     SELECT COALESCE(SUM(sum), 0) INTO total_sum
--     FROM transactions
--     WHERE
--         account_from = account_from
--       AND
--         datetime >= date_trunc('month', transaction_date) AND
--         datetime < date_trunc('month', transaction_date) + INTERVAL '1 month';
--
--     RETURN total_sum;
-- END;
-- $$ LANGUAGE plpgsql;
